# Site settings
title: Gradient-Only Research Group
address: University of Pretoria
email: wilkedn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Department of Mechanical and Aeronautical Engineering<br>
  Centre for Asset and Integrity Management<br>(C-AIM)
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: daniwi79
github_username:  gorgthelab
#instagram_username: 

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman